name: Documentation
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

concurrency:
  group: doc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with: { submodules: recursive }
      - name: setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment.yml
          conda list
      - name: build documentation
        shell: bash -l {0}
        run: |
          cd rtfbook
          jupyter-book build .
          mv _build/html _build/html_
          mkdir -p generated/html
          mv _build/html_ generated/html/rtfbook
          touch generated/html/rtfbook/.nojekyll
      - uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: rtfbook/generated/html/rtfbook
          target-folder: docs
          single-commit: true
        if: ${{ github.event_name == 'push' }}

